data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/user_data55/wangdq/data/nist_zh-en_1.34m/train/middle/train.zh.temp"
    - "/home/user_data55/wangdq/data/nist_zh-en_1.34m/train/middle/train.en.temp"
  valid_data:
    - "/home/user_data55/wangdq/data/nist_zh-en_1.34m/test/mt03.src"
    - "/home/user_data55/wangdq/data/nist_zh-en_1.34m/test/mt03.ref0" # 对ref0文件进行bi-directions 为了loss_validation
  bleu_valid_reference: "/home/user_data55/wangdq/data/nist_zh-en_1.34m/test/mt03.ref"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/public_data/nmtdata/nist_zh-en_1.34m/vocab.zh.bpe.json"
      codes: "/home/public_data/nmtdata/nist_zh-en_1.34m/codes.30k.zh"
      max_n_words: -1
    - type: "bpe"
      dict_path: "/home/public_data/nmtdata/nist_zh-en_1.34m/vocab.en.bpe.json"
      max_n_words: -1
      codes: "/home/public_data/nmtdata/nist_zh-en_1.34m/codes.30k.en"
  max_len:
    - 100
    - 100
  num_refs: 4
  eval_at_char_level: false


model_configs:
  model: DL4MT_1GRU
  d_word_vec: 512
  d_model: 512
  dropout: 0.1
  proj_share_weight: true
  bridge_type: "mlp"

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 256
    warmup_steps: 8000

training_configs:
  max_epochs: 50
  shuffle: true
  use_bucket: true
  batching_key: "tokens"
  batch_size:  2048
  buffer_size: 2048
  update_cycle: 2
  valid_batch_size: 20
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 1 # Start to do BLEU validation after those steps
  bleu_valid_cornfigs:
    max_steps: 150
    beam_size: 4
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
    alpha: 0.0
  num_kept_checkpoints: 10
  num_kept_best_model: 1
  disp_freq: 100 # Frequency to print information
  save_freq: 1000 # Frequency to save the model
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  early_stop_patience: 20